### ISSUE TITLE
Document cluster mode

### ISSUE THREAD

**Issue by MovieStoreGuy** [signalfx/gateway#230]
Looking through the code base, I have noticed several mentions of clustering and etcd and I wanted to know how best to set this up locally to try it out.

I haven't seen any docs on this so far so I'd appreciate any advice on it.

**Comment by mpetazzoni** [comment]
The regular gateway base does not need coordinated clustering. If you're not using our Microservices APM offering, you only need this base Gateway and can simply deploy multiple instances behind an HTTP load balancer for HA and scalability.

When in the context of SignalFx's Microservices APM, you need to use our _Smart Gateway_, which does require coordinated clustering with Etcd. The documentation for that is available on our product documentation site at https://docs.signalfx.com/en/latest/apm/apm-deployment/smart-gateway-clusters.html

We have some work lined up in the future to help rationalize what gets documented where between GitHub vs Product Docs, and in this "base" gateway repository.

**Comment by MovieStoreGuy** [comment]
What I understand from your comment is that this clustered mode isn't intended for the default SignalFx gateway but it is for the smart gateway; this code being the basis of the smart gateway.

If this is the case then why does clustering code exist in the "base" code base instead of being inside the smart gateway code? 

The reason why I wanted to know about clustering is because I wanted the deployment to be durable to AZ outages or instance failures. Furthermore, I haven't ventured too deep within the code but having a HTTP load balancer might not be enough due to the aggregation of metrics before forwarding. In order to get a correct local aggregation, I would have to imagine that I would need some load balancing rules that uses sticky sessions which I don't want to do that where possible.

**Comment by mpetazzoni** [comment]
Clustering-related code in this codebase is just the (unfortunate) result of how the code and the application is structured, forcing us to put this Smart Gateway specific clustering mode into this base repository.

Back to your use-case, there is no metrics aggregation performed by the [regular] Gateway, so a simple HTTP load balancer in front of a tier of Gateway instances is all you need for HA and scale.
